name: Convert JSON to CSV

on:
  push:
    paths:
      - data.json  # This listens for changes to the data.json file

jobs:
  convert-to-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert JSON to CSV
        run: |
          node -e "
            const fs = require('fs');
            const data = require('./data.json');
            const csv = data.map(d => \`\${d.name},\${d.number},\${d.text}\`).join('\n');
            fs.writeFileSync('./data.csv', csv);
          "

      - name: Commit CSV file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data.csv
          git commit -m "Update CSV file"
          git push
